openapi: 3.0.2
info:
  version: 1.0.0
  contact:
    email: estudo.ianmateus@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: '/ZipCode.png'
  description: >
    An sample
tags:
  - name: Query zip code
    description: Address verification via zip code
servers:
  - url: 'http://localhot:3333'
paths:
  /cep/{cep}:
    $ref: paths/cep@{cep}.yaml
