version: '3'

services:
  redis:
    container_name: redis-eureka-dev
    image: redis:alpine
    volumes:
      - $HOME/dataset/eureka/redis:/usr/local/etc/redis
    networks:
      - eureka-database-dev

  backend:
    container_name: backend-eureka-dev
    build: .
    entrypoint: dockerize -wait tcp://redis:6379 -timeout 50s -wait-retry-interval 10s yarn dev:server
    # volumes:
    #   - ./node:/home/node/api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=
    depends_on:
      - redis
    ports:
      - 3333:3333
    networks:
      - eureka-database-dev

networks:
  eureka-database-dev:
    driver: bridge
